import React from "react";
import Head from "next/head";
import Image from "next/image";

import MainNavigation from "./MainNavigation";

const Layout = (props) => {
  return (
    <div className=" w-screen h-screen bg-base-100 py-4 px-4 ">
      <Head>
        <title>Learn Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full flex flex-col w-full">
        <MainNavigation />
        <main className="flex-grow">{props.children}</main>
      </div>
    </div>
  );
};

export default Layout;
